[package]
name = "tqdm"
edition = "2021"
version = "0.5.0"
rust-version = "1.62.1"

readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Python tqdm in Rust"
repository = "https://github.com/mrlazy1708/tqdm"
documentation = "https://docs.rs/tqdm/latest/tqdm"

authors = ["yihengdu"]
keywords = ["tqdm", "progress", "iterator"]
categories = ["accessibility", "command-line-utilities"]

[dependencies]
crossterm = "0.25"
once_cell = "1.18.0"

[build-dependencies]
version_check = "0.9"
